---

- name: Create Workshop application
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'workshop/workshop-application.yaml.j2') | from_yaml }}"
  retries: 10
  delay: 60
  ignore_errors: true
  register: workshop_result
  until: workshop_result is not failed

- name: Print result from the previous task
  ansible.builtin.debug:
    var: workshop_result
