---

- name: Install Demo
  hosts: localhost
  connection: local
  gather_facts: false
  run_once: true

  tasks:
    - name: "Install Demo"
      ansible.builtin.include_role:
        name: ocp4_workload_kafka_workshop
      vars:
        ACTION: create
